name: Testing Actions

on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Caching
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-nodes-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          npm ci
      - name: Create Issue on GitHub
        id: issue
        uses: ./.github/actions/issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: New Custom Title
          body: Interesting Body Section of Issue
          assignees: |
            Tom
            Peter
      - name: Hello World Action
        id: hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: Simon
      - name: Output Hello World and Issue
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo "Issue: ${{ steps.issue.outputs.issue }}"
          echo $HELLO
